### ISSUE TITLE
Add sponsorship biographies

### ISSUE THREAD

**Issue by ThatSealgair** [uqmars/uqmars.github.io#42]
Turbo tier sponsors are supposed to get a dedicated page on the website.

**Comment by The-AhmadAA** [comment]
Will commence work on this today to have up by Monday

**Comment by The-AhmadAA** [comment]
Sponsor page created, biographies pulled directly from websites. Might need to consider getting sponsorships team to write original blurbs based on our relationship with sponsors. Pull request created for merge of base page.
