### ISSUE TITLE
Proposed change to the contact section on page footer

### ISSUE THREAD

**Issue by The-AhmadAA** [uqmars/uqmars.github.io#49]
![image](https://user-images.githubusercontent.com/111224176/235350116-49fb8d79-2368-4cb0-8c10-e9b25c8dee31.png)

proposed to improve visibility and layout

**Comment by q-horton** [comment]
That looks nice, may want to increase the opacity of the tabs a bit though as white on gold can be a bit tough to read.

**Comment by q-horton** [comment]
<img width="877" alt="image" src="https://user-images.githubusercontent.com/106427075/235351614-9dd31708-16b8-4044-afb2-db0093b885d3.png">
The background image doesn't seem to be coming up.

**Comment by The-AhmadAA** [comment]
That's an existing problem with some of the pages, I'll raise it as a separate issue.
